### ISSUE TITLE
Read initial dataref value

### ISSUE THREAD

**Issue by EvenAR** [vranki/ExtPlane#13]
Is there any way to read values that has not been changed? For example, how can I detect if landing gear is deployed or not if my client application is started while the aircraft is in the air? When I subscribe to "sim/aircraft/parts/acf_gear_deploy" I'm only able to read the landing gear position while it's moving.

Btw, I love your project. Great work! 👍

**Comment by vranki** [comment]
Hm, IIRC it should send the value after subscribing, but of course there can be a bug. Should be studied. 
Thanks for feedback and reporting this! 

If you know c++, you can take a look if you find the bug and send a pull request for it.

**Comment by sfo** [comment]
You will get the desired initial update only for the first client that subscribes to a dataref. For the moment, make sure your application is the first one that reads the desired values. Maybe you have to kill other clients first (also ensure to kill old instances of your client).

There is a little logical issue regarding value change notifications. Those are handled globally across all clients that subscribe to the same dataref. While the first connected client receives the update from an invalid initial value to the actual value of the dataref, all following connections during that session will never receive a notification again, because the value of the global dataref object does not change.

To fix the issue, I suggest the following: Around [line 88 in tcpclient.cpp](https://github.com/vranki/ExtPlane/blob/master/tcpclient.cpp#L88) a mechanism could be introduced that forces an update notification to the client even if the value of the dataref object didn't change. That way, a client subscribing to an already subscribed dataref would receive an initial value update.

Maybe I can find some time to implement it, not sure when this will happen.

**Comment by EvenAR** [comment]
Thanks for the quick response! The problem was indeed that I had several client instances connected at the same time. For most of the users it will most likely not be a problem, but a fix would be very nice. I know C++ so I could take a look at it. Just need to wait for Qt to install, which takes ages on my internet connection.. :p

**Comment by vranki** [comment]
I'm working on some new features and going to fix this.

**Comment by markcellis** [comment]
I ran into this too and would like to see it fixed. If you don't have time to work on it I can take a stab at it, just let me know. I already corrected a different problem in the Qt client code and sent a pull request.

**Comment by markcellis** [comment]
Just to add to this, I also ran into this enhancing ExtPlane Panel. On one panel I had two panel items that each subscribed to the same dataref. When the 2nd one subscribed to the dataref it did not get back an initial value. I believe this is all related to your above suggested fix. I just want to say that I would re-broadcast the dataref on subscription even if the same client was already subscribed. It sounded like that was how you were planning on fixing it anyways.

**Comment by Agamennon** [comment]
It would also be awesome if you could have a GET dataref command to get the value without subscribing.

**Comment by vranki** [comment]
Could you create a new ticket about GET dataref? With a suggestion on how it should work. Probably just like sub and it would update value once?

**Comment by vranki** [comment]
Btw this issue should be now fixed in master branch.. Please reopen this ticket if it still happens.
