### ISSUE TITLE
Display dataref value with label

### ISSUE THREAD

**Issue by maha99tests** [vranki/ExtPlane#18]
Fantastic project, just saved me tons of headaches while flying.

Just found a simple requirement missing. I want to be able ti display data ref values with labels.

My current best option is to use debug data refs but it prints the whole data ref name. Can you add a label setting to this? Would be damn useful.

**Comment by vranki** [comment]
Hi, 

If the issue is about the graphical ExtPlane-Panel app, please file a bug to https://github.com/vranki/ExtPlane-Panel . This is about the plugin which doesn't display anything.

If i understand correctly the issue is about DatarefDebugger and it should display a custom label instead of the ref name?

**Comment by bitonator** [comment]
Got it, I'll file it in the panel project.
